const SOCKET_URL = "https://mlsa-file-share-socket-server.herokuapp.com/";
const WELCOME = "welcome";
const WELCOME_REPLY_SENDER = "welcome from sender";
const WELCOME_REPLY_RECEIVER = "welcome from receiver";
const SENDER_SIGNAL = "SENDER SIGNAL";
const SENDER_SIGNAL_SOCKET_REPLY = "SENDING SENDER SIGNAL";
const RECEIVER_SIGNAL = "RECEIVING SIGNAL";
const RECEIVER_SIGNAL_SOCKET_REPLY = "SENDING RECEIVER SIGNAL";
const COMPLETED = "Done!";
const CREATE_ROOM = "CREATE ROOM";
const RECEIVER_JOINED = "RECEIVER JOINED";
const MAKE_CONNECTION = "MAKE CONNECTION";
const RECEIVED_FILE = "RECEIVED_FILE";

module.exports = {
  SOCKET_URL,
  WELCOME,
  WELCOME_REPLY_SENDER,
  WELCOME_REPLY_RECEIVER,
  SENDER_SIGNAL,
  SENDER_SIGNAL_SOCKET_REPLY,
  RECEIVER_SIGNAL,
  RECEIVER_SIGNAL_SOCKET_REPLY,
  COMPLETED,
  CREATE_ROOM,
  RECEIVER_JOINED,
  MAKE_CONNECTION,
  RECEIVED_FILE,
};
